### ISSUE TITLE
No module named 'fastreid.modeling.backbones.mixstyle'

### ISSUE THREAD

**Issue by maligawork** [ZhenyuX1E/PoseTrack#1]
Hello, and thank you for your work. Can you explain to me where the mixstyle module is for your pretrained ReID network?

**Comment by ZhenyuX1E** [comment]
@maligawork Hello, thanks for your feedback. We have uploaded the missing python file (fast-reid/fastreid/modeling/backbones/mixstyle.py). Please download the latest version of the code or manually copy this file to your directory.

**Comment by maligawork** [comment]
@ZhenyuX1E thank you!
