### ISSUE TITLE
Pretrained model link broken

### ISSUE THREAD

**Issue by Adil42s** [ZhenyuX1E/PoseTrack#3]
您好，似乎预训练的 reid 模型链接不起作用，请您提供新的链接来下载 reid 模型。非常感谢

**Comment by ZhenyuX1E** [comment]
您好，模型链接现在应该恢复正常了，谢谢提醒。
Hello, the model link is available now. Thanks for reminding.

**Comment by Adil42s** [comment]
thanks for your kind reply.
