### ISSUE TITLE
兄弟，你的这个工作在3090或者4090上可以实时运行吗？

### ISSUE THREAD

**Issue by dididichufale** [ZhenyuX1E/PoseTrack#4]
兄弟你好，你这个项目可以实时运行吗，我想把你的工作改成跨镜头车辆跟踪，请问可行吗

**Comment by dididichufale** [comment]
最多两张4090显卡或者3090显卡运行，希望兄弟可以回答我，谢谢！

**Comment by dididichufale** [comment]
作者您好，我粗略的看了您的代码，真的写的太棒了。但是我发现您的代码好像是建立在两个视角必须有有一部分面积重叠的情况，那么假如两个视角没有重叠，这个时候您的代码人物可以匹配到吗

**Comment by ZhenyuX1E** [comment]
> 作者您好，我粗略的看了您的代码，真的写的太棒了。但是我发现您的代码好像是建立在两个视角必须有有一部分面积重叠的情况，那么假如两个视角没有重叠，这个时候您的代码人物可以匹配到吗

是的，我们的工作主要针对有重叠区域的多相机系统。如果您希望应用在无重叠区域的多相机车辆跟踪上，您可以参考2022年和之前的aicity challenge中的工作。
关于实时运行，我们暂时没有测试过运行的速度，因为推理的速度与场景中的行人数量有关。如果您对系统使用tensorRT以及一定程度的代码优化，可能可以达到实时运行的效果。

**Comment by dididichufale** [comment]
谢谢您的回答，但是aicity challenge22年之前的工作我能查到的全是离线版本的工作，不能用在实际的生产环境中，我需要实时接rtsp流运行。我想问一哈，假如有一条口字形公路，我放置8个相机分别在口字的四个拐角和四条路的中间区域。做到每两个相机都有一部分重叠区域，难么您的代码可以跨境头跟踪到吗。另外，script文件夹下standard_detection.sh文件单词打错了，需要修正一下 ，不然要报错，希望作者可以回答我一下，谢谢.

**Comment by ZhenyuX1E** [comment]
> 谢谢您的回答，但是aicity challenge22年之前的工作我能查到的全是离线版本的工作，不能用在实际的生产环境中，我需要实时接rtsp流运行。我想问一哈，假如有一条口字形公路，我放置8个相机分别在口字的四个拐角和四条路的中间区域。做到每两个相机都有一部分重叠区域，难么您的代码可以跨境头跟踪到吗。另外，script文件夹下standard_detection.sh文件单词打错了，需要修正一下 ，不然要报错，希望作者可以回答我一下，谢谢.

您好，要应用于您所说的场景，您需要将系统使用的检测、姿态估计、reid模型更换为适用于车辆场景的模型，并重新适配输出。谢谢您对代码中错误的提醒。
