### ISSUE TITLE
About detection and pose estimation stage

### ISSUE THREAD

**Issue by manhdan226** [ZhenyuX1E/PoseTrack#5]
First, congratulations.

Would you mind sharing your detection and pose estimation output? My computer is not strong enough, so it takes a very long time to complete the detection and pose estimation stage.

Thank you so much

**Comment by ZhenyuX1E** [comment]
Thank you for your attention. Regarding the detection and pose estimation output, unfortunately due to storage limitations, we have already deleted these results (which takes over 500 GB). You can try running it on a small subset of the dataset.

**Comment by manhdan226** [comment]
Yes, I see. Thank you for your reply. I'm trying with a part of the validation and the whole test set.
