### ISSUE TITLE
About the evaluation system

### ISSUE THREAD

**Issue by manhdan226** [ZhenyuX1E/PoseTrack#6]
Hi, sorry to bother you. 

Although the competition is over, I still want to test my results.
But, I have a problem with the evaluation system.
 - When I send .txt file, the uploading process is failed due to the huge size.
 - When I tried with .tar.gz, I receive the message _raise ReadError("file could not be opened successfully")_. I'm using this command: tar -czvf track1.tar.gz track1.txt
 
Can you share how you submit to the evaluation system?

Thank you so much.

**Comment by ZhenyuX1E** [comment]
Hello, we submitted the result in zip format and we didn't encounter any problem :)
